Bump org.jetbrains.kotlin:kotlin-gradle-plugin from 2.3.21 to 2.4.0 (#201)
Bumps
[org.jetbrains.kotlin:kotlin-gradle-plugin](https://github.com/JetBrains/kotlin)
from 2.3.21 to 2.4.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/releases">org.jetbrains.kotlin:kotlin-gradle-plugin's
releases</a>.</em></p>
<blockquote>
<h2>Kotlin 2.4.0</h2>
<h2>Changelog</h2>
<h3>Analysis API</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83867"><code>KT-83867</code></a>
OVERLOAD_RESOLUTION_AMBIGUITY false positive with assertEquals in IJ
repo</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83723"><code>KT-83723</code></a>
[Analysis API] Enable experimental KDoc resolver by default</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83388"><code>KT-83388</code></a>
Analysis API: properly support KMP in KotlinPackageProvider</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-65683"><code>KT-65683</code></a>
Analysis API: Dangling file session creation causes a
<code>computeIfAbsent</code> contract violation</li>
</ul>
<h3>Analysis API. Code Compilation</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78946"><code>KT-78946</code></a>
Evaluation of variable with local class in type parameter leads to
InventNamesForLocalClasses exception</li>
</ul>
<h3>Analysis API. FIR</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-68260"><code>KT-68260</code></a>
K2 AA: InvalidFirElementTypeException “For CALLABLE_REFERENCE_EXPRESSION
with text <code>::lam1</code>, unexpected element of type: no element
found” with illegal callable reference call</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-70896"><code>KT-70896</code></a>
AA: False positive deprecation warning with override of built-in method
in JDK mapped class</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84711"><code>KT-84711</code></a>
K2 IDE sometimes loses FIR plugin-generated declarations after file
changes</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84625"><code>KT-84625</code></a>
Analysis API: collectDesignationPath fails for nested classes inside
plugin-generated top-level classes</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84596"><code>KT-84596</code></a>
Improve K2 Jooq completion performance</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84525"><code>KT-84525</code></a>
KaValueParameterSymbol#getHasSynthesizedName returns false for
FirDeclarationOrigin.SubstitutionOverride.DeclarationSite</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83546"><code>KT-83546</code></a>
Kotlin analysis reach ClsCustomNavigationPolicy</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84259"><code>KT-84259</code></a>
Move CommonDefaultImportsProvider to the frontend independent
module</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-82945"><code>KT-82945</code></a>
Analysis API: KotlinIllegalArgumentExceptionWithAttachments: Expected
FirResolvedTypeRef with ConeKotlinType but was FirUserTypeRefImpl</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-71135"><code>KT-71135</code></a>
AA: exception from sealed inheritors checker when
<code>analyzeCopy</code></li>
</ul>
<h3>Analysis API. Infrastructure</h3>
<h4>Fixes</h4>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83905"><code>KT-83905</code></a>
Analysis API: Improve UX with test data</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84913"><code>KT-84913</code></a>
Extract compiler classes used by the PSI &amp; Analysis API to a
separate module</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-64986"><code>KT-64986</code></a>
Analysis API: Implement Analysis API tests for different KMP
Platforms</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84776"><code>KT-84776</code></a>
The test data manager misses the redundancy check in the update
mode</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84962"><code>KT-84962</code></a>
The test data manager misses -ea flag</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84388"><code>KT-84388</code></a>
Preserve the EOF status in the test data manager to avoid extra
changes</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84362"><code>KT-84362</code></a>
Analysis API tests produce many warnings due to &quot;not yet loaded
registry&quot;</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84279"><code>KT-84279</code></a>
Test Data Manager fails on a clean build</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83913"><code>KT-83913</code></a>
Exclude compiler-based Analysis API tests from Git tracking</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-80379"><code>KT-80379</code></a>
Extract per-module test generators for AA tests</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84120"><code>KT-84120</code></a>
Move CLI modules out of kotlin-compiler-fe10-for-ide</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-83200"><code>KT-83200</code></a>
Track external dependencies of the Analysis API modules</li>
</ul>
<h3>Analysis API. Light Classes</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-82434"><code>KT-82434</code></a>
Light classes should prefer enum entries to properties</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84200"><code>KT-84200</code></a>
SLC: return type is not boxed for delegated methods with generic
original method</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-72451"><code>KT-72451</code></a>
&quot;CCE: class PsiPrimitiveType cannot be cast to class
PsiClassType&quot; with same-named enum class and typealias</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/blob/v2.4.0/ChangeLog.md">org.jetbrains.kotlin:kotlin-gradle-plugin's
changelog</a>.</em></p>
<blockquote>
<h2>2.4.0-RC2</h2>
<h3>Backend. J2KLIB</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-86367"><code>KT-86367</code></a>
[JKLIB] kotlin.Cloneable built-in class not found</li>
</ul>
<h3>Compose compiler</h3>
<ul>
<li><a
href="https://issuetracker.google.com/issues/511102714"><code>b/511102714</code></a>
Made the default stability of non-final classes <code>Unknown</code>
instead of <code>Stable</code></li>
</ul>
<h3>Tools. Build Tools API</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-86395"><code>KT-86395</code></a>
[BTA] forward-compatibility violation: NoSuchMethodError on
JvmSnapshotBasedIncrementalCompilationConfiguration.<!-- raw HTML
omitted --> breaks IC</li>
</ul>
<h3>Tools. Gradle</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-86346"><code>KT-86346</code></a>
Compiler warnings printed twice in console — once as <code>w:</code> and
again as Gradle &quot;Problem found:&quot; block</li>
</ul>
<h3>Tools. Gradle. BCV</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-86268"><code>KT-86268</code></a>
ABI validation tasks fail with Unsupported platform toolchain type when
using kotlin.compilerVersion pointing to an older compiler after BTA
migration in 2.4.0-Beta2</li>
</ul>
<h3>Tools. Gradle. Wasm</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-86457"><code>KT-86457</code></a>
[Wasm, Gradle] BinaryenExec.standardOutput is silently ignored after
migration to Gradle Workers</li>
</ul>
<h2>2.4.0-RC</h2>
<h3>Backend. J2KLIB</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84877"><code>KT-84877</code></a>
[J2KLIB] Remove withKotlinBuiltinsHack present in JKlibIrLinker.kt</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-85846"><code>KT-85846</code></a>
Tests failing with fake override property missing accessors or backing
field</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-85717"><code>KT-85717</code></a>
IllegalStateException due to already bound symbol</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-86204"><code>KT-86204</code></a>
[JKlib] Propagate private members from dependecies in the IR tree</li>
</ul>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-86210"><code>KT-86210</code></a>
Update -Xannotation-default-target CLI parameter doc</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-85948"><code>KT-85948</code></a>
Contracts in 2.4 stdlib is not compatible with 2.3 compiler</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-85957"><code>KT-85957</code></a>
Contract on function is getting discarded if any of effect declarations
is unknown</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-86130"><code>KT-86130</code></a>
False positive UNINITIALIZED_ENUM_COMPANION on LV 2.3 and lower</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84860"><code>KT-84860</code></a>
False positive UNINITIALIZED_ENUM_COMPANION in enum access with explicit
receiver in enum initializer when enum class has a companion</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84319"><code>KT-84319</code></a>
Add JVM target bytecode version 26</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-85825"><code>KT-85825</code></a>
Context parameter lambda loses context type when wrapped in nested
<code>run</code> blocks</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-84960"><code>KT-84960</code></a>
Property contract leaks unsubstituted type parameter in smart cast</li>
</ul>
<h3>Compose compiler</h3>
<ul>
<li><a
href="https://issuetracker.google.com/issues/509945632"><code>b/509945632</code></a>
Do not generate groups in inline lambdas without
<code>@Composable</code> calls</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/JetBrains/kotlin/commit/add726ca8c82922b6ab4cb2a27ae738d6a780817"><code>add726c</code></a>
Add ChangeLog for 2.4.0-RC2</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/69a4a81ef24de99aec8c05d175239ddfe29c876d"><code>69a4a81</code></a>
[Wasm] Add binaryen per-file arguments</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/8907c635d4a7101e318b895c2829fc917c64e92c"><code>8907c63</code></a>
[KGP] Suppress duplicate compiler warning output when --warning-mode=all
is a...</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/f9bef128ea07e986602e3c6524cea85038308ae6"><code>f9bef12</code></a>
[KGP] Add failing test for duplicate compiler warning output via
Problems API</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/7fe49c227af21127ab4eb39a2da693e14a068fe4"><code>7fe49c2</code></a>
KT-86268: Use 2.4.0 toolchain for abiValidation with older CVs</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/13d25e2c581f55cecbe80bf9e9359af14fa00ef9"><code>13d25e2</code></a>
KT-86268: Regression test added</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/f7d1a76541b33871e9be156143ceb904588c4863"><code>f7d1a76</code></a>
[JKlib] Fix JAR deserializer configuration.</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/5cec663affd3fe9e7b7342e336ad4952ae59a2ad"><code>5cec663</code></a>
[JKlib] Wire up JvmBuiltInClassDescriptorFactory</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/ef146114de8b0db65ff96b21a67c87da95a8c82e"><code>ef14611</code></a>
Make the default stability of non-final classes <code>Unknown</code>
instead of <code>Stable</code></li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/d76473afd242d7655c975a6346ed4b24c35573ca"><code>d76473a</code></a>
[Gradle] Fix GeneralNativeIT.shouldAllowToOverrideDownloadUrl test
failures</li>
<li>Additional commits viewable in <a
href="https://github.com/JetBrains/kotlin/compare/v2.3.21...v2.4.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.jetbrains.kotlin:kotlin-gradle-plugin&package-manager=gradle&previous-version=2.3.21&new-version=2.4.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>